version: '3'
services:
  hydra:
    build:
      args:
        user: hydra
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: hydra
    working_dir: /var/www
    volumes:
      - ./:/var/www/public
    networks:
      - hydra
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - hydra
  webserver:
    image: nginx:1.17-alpine
    ports:
      - 8000:80
    volumes:
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - hydra
networks:
  hydra:
    driver: bridge
