version: '3'
services:
  hydra:
    build:
      context: ../..
      dockerfile: ./.docker/dev/Dockerfile
    image: hydra
    volumes:
      - ../nginx.conf:/etc/nginx/conf.d/default.conf
      - ../..:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - database
    networks:
      - hydra
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      - hydra
networks:
  hydra:
    driver: bridge
