name: publish
on:
  push:
    branches:
      - master
      - develop
      - release/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo ::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF##*/})
    - uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        name: docker.pkg.github.com/houfio/hydra/hydra
        username: houfio
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        dockerfile: .docker/env/prod/Dockerfile
        context: .
        tags: "${{ BRANCH_NAME }}"
